defaults: &defaults
  adapter: mysql2
  username: translations
  password: translations
  host: localhost

development:
  <<: *defaults
  database: x_development

test:
  <<: *defaults
  database: x_test

production:
  <<: *defaults
  database: x_production
