# encoding: utf-8
# # This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
#

# Languages
languages = [
  ['English', 'en'],
  ['German', 'de'],
  ['French', 'fr'],
  ['Dutch', 'nl'],
  ['Italian', 'it'],
  ['Spanish', 'es'],
  ['Polish', 'pl'],
  ['Russian', 'ru'],
  ['Japanese', 'ja'],
  ['Portuguese', 'pt'],
  ['Portuguese', 'pt-br'],
  ['Swedish', 'sv'],
  ['Chinese', 'zh'],
  ['Catalan', 'ca'],
  ['Ukrainian', 'uk'],
  ["Norwegian (Bokmål)", 'no'],
  ['Finnish', 'fi'],
  ['Vietnamese', 'vi'],
  ['Czech', 'cs'],
  ['Hungarian', 'hu'],
  ['Korean', 'ko'],
  ['Indonesian', 'id'],
  ['Turkish', 'tr'],
  ['Romanian', 'ro'],
  ['Persian', 'fa'],
  ['Arabic', 'ar'],
  ['Danish', 'da'],
  ['Esperanto', 'eo'],
  ['Serbian', 'sr'],
  ['Lithuanian', 'lt'],
  ['Slovak', 'sk'],
  ['Malay', 'ms'],
  ['Hebrew', 'he'],
  ['Bulgarian', 'bg'],
  ['Slovenian', 'sl'],
  ['Volapük', 'vo'],
  ['Kazakh', 'kk'],
  ['Waray-Waray', 'war'],
  ['Basque', 'eu'],
  ['Croatian', 'hr'],
  ['Hindi', 'hi'],
  ['Estonian', 'et'],
  ['Azerbaijani', 'az'],
  ['Galician', 'gl'],
  ['Simple English', 'simple'],
  ['Norwegian [Nynorsk)', 'nn'],
  ['Thai', 'th'],
  ['Newar / Nepal Bhasa', 'new'],
  ['Greek', 'el'],
  ['Aromanian', 'roa-rup'],
  ['Latin', 'la'],
  ['Occitan', 'oc'],
  ['Tagalog', 'tl'],
  ['Haitian', 'ht'],
  ['Macedonian', 'mk'],
  ['Georgian', 'ka'],
  ['Serbo-Croatian', 'sh'],
  ['Telugu', 'te'],
  ['Piedmontese', 'pms'],
  ['Cebuano', 'ceb'],
  ['Tamil', 'ta'],
  ['Belarusian [Taraškievica)', 'be-x-old'],
  ['Breton', 'br'],
  ['Latvian', 'lv'],
  ['Javanese', 'jv'],
  ['Albanian', 'sq'],
  ['Belarusian', 'be'],
  ['Marathi', 'mr'],
  ['Welsh', 'cy'],
  ['Luxembourgish', 'lb'],
  ['Icelandic', 'is'],
  ['Bosnian', 'bs'],
  ['Yoruba', 'yo'],
  ['Malagasy', 'mg'],
  ['Aragonese', 'an'],
  ['Bishnupriya Manipuri', 'bpy'],
  ['Lombard', 'lmo'],
  ['West Frisian', 'fy'],
  ['Bengali', 'bn'],
  ['Ido', 'io'],
  ['Swahili', 'sw'],
  ['Gujarati', 'gu'],
  ['Malayalam', 'ml'],
  ['Western Panjabi', 'pnb'],
  ['Afrikaans', 'af'],
  ['Low Saxon', 'nds'],
  ['Sicilian', 'scn'],
  ['Urdu', 'ur'],
  ['Kurdish', 'ku'],
  ['Cantonese', 'zh-yue'],
  ['Armenian', 'hy'],
  ['Quechua', 'qu'],
  ['Sundanese', 'su'],
  ['Nepali', 'ne'],
  ['Zazaki', 'diq'],
  ['Asturian', 'ast'],
  ['Tatar', 'tt'],
  ['Neapolitan', 'nap'],
  ['Irish', 'ga'],
  ['Chuvash', 'cv'],
  ['Samogitian', 'bat-smg'],
  ['Walloon', 'wa'],
  ['Amharic', 'am'],
  ['Kannada', 'kn'],
  ['Alemannic', 'als'],
  ['Buginese', 'bug'],
  ['Burmese', 'my'],
  ['Interlingua', 'ia'],
]

Language.delete_all
languages.each_with_index do |language,i|
 Language.create(id: i+1, name: language[0], abbreviation: language[1])
end
# Fix Languages id sequence in the db
ActiveRecord::Base.connection.reset_pk_sequence!("languages")
